# main menu config
screen=Petrova_Settings

# show settings
screen.Petrova_Settings=ENABLE_ADRIAN_ATMOSPHERE ENABLE_PETROVA_LINE ENABLE_ASTROPHAGE_SWARM REDSHIFT_POWER SWARM_DENSITY
sliders=REDSHIFT_POWER SWARM_DENSITY